const CAR_DATA = {
  updated: "September 9, 2026 · 10:00 PM ET · live dealer refresh",
  summary: [
    "Fresh dealer-first reindex completed tonight. Championship's current inventory no longer contains the previously ranked 2021 Kia Sportage LX or 2020 Hyundai Santa Fe Limited, so both were purged rather than carried forward from stale data.",
    "The 2018 Ford Fusion Hybrid S remains #1. Its dealer-owned VDP was crawled yesterday and still shows $14,498 including the $498 processing fee, 44,463 miles and 42 MPG combined.",
    "The strongest newly verified crossover is a 2018 Honda CR-V EX at Moore with only 97,903 miles, AWD and a current $19,586 Moore Value Price. It replaces the older stale CR-V EX entry that had 125,431 miles.",
    "A 2018 Honda CR-V EX-L AWD at Moore enters at #3 at $18,384 with 123,655 miles. It adds leather and higher trim equipment while remaining below the $20,000 ceiling.",
    "Championship's best current fit is a 2017 Honda CR-V EX-L with navigation at $18,218 final price and 135,920 miles. It is FWD, so it ranks below the Moore AWD Hondas despite its equipment.",
    "The 2018 Honda CR-V LX remains a fallback at $16,786 and 136,647 miles. Championship's current inventory was re-enumerated from its dealer-owned search endpoint before ranking."
  ],
  cars: [
    {rank:1,year:2018,vehicle:"Ford Fusion Hybrid S",price:14498,miles:44463,type:"Sedan",fuel:"Hybrid",drive:"FWD",dealer:"Moore Automotive Team",area:"Owensboro, KY",vin:"3FA6P0UUXJR282061",assessment:"Best overall value. Dealer-owned VDP remains live at $14,498 including processing fee, with only 44.5k miles and 42 MPG combined.",url:"https://www.donmoorehonda.com/used-Owensboro-2018-Ford-Fusion%2BHybrid-S-3FA6P0UUXJR282061"},
    {rank:2,year:2018,vehicle:"Honda CR-V EX",price:19586,miles:97903,type:"Small crossover",fuel:"Gas",drive:"AWD",dealer:"Moore Automotive Team",area:"Owensboro, KY",vin:"7FARW2H59JE022118",assessment:"Best current AWD crossover fit. Only 97.9k miles, Honda reliability, adaptive cruise, blind-spot monitoring and AWD. Near the budget ceiling but materially lower mileage than the other SUVs.",url:"https://www.donmoorehonda.com/searchused.aspx"},
    {rank:3,year:2018,vehicle:"Honda CR-V EX-L",price:18384,miles:123655,type:"Small crossover",fuel:"Gas",drive:"AWD",dealer:"Moore Automotive Team",area:"Owensboro, KY",vin:"2HKRW2H86JH658521",assessment:"Strong AWD alternative with leather, adaptive cruise and 123.7k miles. Better equipment and lower price than the lower-mile EX, but the extra 25.8k miles matter.",url:"https://www.donmoorehonda.com/searchused.aspx"},
    {rank:4,year:2017,vehicle:"Honda CR-V EX-L w/Navigation",price:18218,miles:135920,type:"Small crossover",fuel:"Gas",drive:"FWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"5J6RW1H8XHL015678",assessment:"Best current Championship fit. Final price includes its $499 processing fee. Leather, navigation and good fuel economy, but FWD and 135.9k miles keep it below the Moore AWD options.",url:"https://www.championshipautos.com/searchused.aspx"},
    {rank:5,year:2018,vehicle:"Honda CR-V LX",price:16786,miles:136647,type:"Small crossover",fuel:"Gas",drive:"FWD",dealer:"Moore Automotive Team",area:"Owensboro, KY",vin:"2HKRW5H36JH414504",assessment:"Budget crossover fallback. Current dealer inventory shows $16,786 including processing fee and 136.6k miles. Lower trim, FWD and high mileage make the other CR-Vs preferable.",url:"https://www.donmoorehonda.com/searchused.aspx"}
  ]
};