const CAR_DATA = {
  updated: "September 13, 2026 · 5:00 AM ET · dealer-first refresh",
  summary: [
    "Fresh dealer-first refresh completed September 13. Champion Ship Auto Sales 54 was enumerated first from its current used-inventory endpoint and sitemap, then qualifying $10k-$20k sedans and small crossovers were re-ranked from scratch using current dealer-owned VDPs where available.",
    "The 2018 Ford Fusion Hybrid S remains #1 at $14,498 with only 44,463 miles and 42 MPG combined. Its dealer-owned Don Moore VDP was crawled yesterday and still shows the same price, VIN and mileage.",
    "The biggest Championship addition is a second 2021 Kia Sportage LX AWD: VIN KNDPMCACXM7928151 is live today at $17,939 final with only 76,104 miles. It moves to #3 and is a materially stronger AWD value than the older high-mileage crossovers previously near the top of the board.",
    "A 2021 Nissan Kicks SV also enters at #4 at $14,810 final with 88,922 miles and 31/36 MPG. It is FWD, but the price, mileage and efficiency make it one of the better current commuter/crossover fits.",
    "The 2023 Volkswagen Jetta SE is now fully dealer-verified at $18,499 final with 115,428 miles and 29/40 MPG, so it returns to the ranked board.",
    "The previously carried Moore 2018 CR-V EX-L was removed because its old Don Moore VDP now returns 404 and I could not verify a replacement dealer-owned VDP. The Moore CR-V LX was also withheld because current secondary pricing conflicts with the older dealer-page price.",
    "Championship's 2020 Mazda CX-5 Grand Touring Reserve remains in the current dealer sitemap and secondary listings still corroborate $17,561, 139,800 miles and AWD; its exact dealer VDP remains the published click-through link but is intermittently inaccessible to the crawler."
  ],
  cars: [
    {rank:1,year:2018,vehicle:"Ford Fusion Hybrid S",price:14498,miles:44463,type:"Sedan",fuel:"Hybrid",drive:"FWD",dealer:"Moore Automotive Team",area:"Owensboro, KY",vin:"3FA6P0UUXJR282061",assessment:"Best overall value. Dealer VDP remains live at $14,498 including the processing fee, only 44.5k miles, and 42 MPG combined.",url:"https://www.donmoorehonda.com/used-Owensboro-2018-Ford-Fusion%2BHybrid-S-3FA6P0UUXJR282061"},
    {rank:2,year:2022,vehicle:"Kia Forte LXS",price:16616,miles:70667,type:"Sedan",fuel:"Gas",drive:"FWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"3KPF24AD9NE478820",assessment:"Dealer VDP verified today at $16,616 final, 70.7k miles and 29/39 MPG. Strong age/mileage/value balance.",url:"https://www.championshipautos.com/used-Owensboro-2022-Kia-Forte-LXS-3KPF24AD9NE478820"},
    {rank:3,year:2021,vehicle:"Kia Sportage LX",price:17939,miles:76104,type:"Small crossover",fuel:"Gas",drive:"AWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"KNDPMCACXM7928151",assessment:"Best newly verified AWD value. Exact dealer VDP is live today at $17,939 final with only 76.1k miles, AWD and modern safety/phone integration.",url:"https://www.championshipautos.com/used-Owensboro-2021-Kia-Sportage-LX-KNDPMCACXM7928151"},
    {rank:4,year:2021,vehicle:"Nissan Kicks SV",price:14810,miles:88922,type:"Small crossover",fuel:"Gas",drive:"FWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"3N1CP5CV9ML513045",assessment:"Excellent budget commuter/crossover fit. Dealer VDP is live today at $14,810 final, 88.9k miles and 31/36 MPG with adaptive cruise, blind-spot warning and phone integration.",url:"https://www.championshipautos.com/used-Owensboro-2021-Nissan-Kicks-SV-3N1CP5CV9ML513045"},
    {rank:5,year:2024,vehicle:"Kia Soul LX",price:16499,miles:108485,type:"Small crossover/hatchback",fuel:"Gas",drive:"FWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"KNDJ23AU6R7908751",assessment:"Newest verified sub-$20k option. Dealer VDP is live today at $16,499 final with 108.5k miles, 29/35 MPG and active-safety equipment.",url:"https://www.championshipautos.com/used-Owensboro-2024-Kia-Soul-LX-KNDJ23AU6R7908751"},
    {rank:6,year:2023,vehicle:"Volkswagen Jetta SE",price:18499,miles:115428,type:"Sedan",fuel:"Gas",drive:"FWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"3VWEM7BU9PM031951",assessment:"Back on the board after full dealer verification. Exact VDP shows $18,499 final, 115.4k miles and 29/40 MPG with adaptive cruise, blind-spot monitoring and heated seats.",url:"https://www.championshipautos.com/used-Owensboro-2023-Volkswagen-Jetta-SE-3VWEM7BU9PM031951"},
    {rank:7,year:2018,vehicle:"Honda CR-V EX-L",price:19767,miles:129798,type:"Small crossover",fuel:"Gas",drive:"AWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"5J6RW2H83JL031183",assessment:"Dealer VDP is live at $19,767 final with 129.8k miles, AWD, leather, Honda Sensing and power liftgate. Strong reliability reputation, but mileage and price hold it below the newer choices.",url:"https://www.championshipautos.com/used-Owensboro-2018-Honda-CR%2BV-EX%2BL-5J6RW2H83JL031183"},
    {rank:8,year:2020,vehicle:"Hyundai Santa Fe Limited",price:17494,miles:121755,type:"Small crossover",fuel:"Gas",drive:"AWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"5NMS5CAD7LH214145",assessment:"Exact dealer VDP remains live at $17,494 final and 121.8k miles. AWD and Limited-trim equipment are appealing, but mileage and long-term reliability risk keep it below the newer Sportage.",url:"https://www.championshipautos.com/used-Owensboro-2020-Hyundai-Santa%2BFe-Limited-5NMS5CAD7LH214145"},
    {rank:9,year:2020,vehicle:"Mazda CX-5 Grand Touring Reserve",price:17561,miles:139800,type:"Small crossover",fuel:"Gas",drive:"AWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"JM3KFBAY0L0850195",assessment:"Still present in Championship's current sitemap and secondary listings corroborate $17,561, 139.8k miles and AWD. Turbo, AWD and high trim are positives; mileage is the main drawback.",url:"https://www.championshipautos.com/used-Owensboro-2020-+-Mazda+CX+5-Grand+Touring+Reserve-JM3KFBAY0L0850195"},
    {rank:10,year:2021,vehicle:"Kia Sportage LX",price:14247,miles:132477,type:"Small crossover",fuel:"Gas",drive:"AWD",dealer:"Champion Ship Auto Sales 54",area:"Owensboro, KY",vin:"KNDPMCAC5M7906543",assessment:"Cheapest verified AWD crossover. Dealer VDP is live today at $14,247 final and 132.5k miles; attractive price, but substantially more mileage than the other 2021 Sportage.",url:"https://www.championshipautos.com/used-Owensboro-2021-Kia-Sportage-LX-KNDPMCAC5M7906543"}
  ]
};